package com.kzhovn.todoapp.recurrence

import com.kzhovn.todoapp.data.RecurrenceType

enum class RecurrencePreset { NONE, DAILY, WEEKLY, MONTHLY, EVERY_N_DAYS, AFTER_COMPLETION_N_DAYS }

data class RecurrenceSelection(val preset: RecurrencePreset, val n: Int = 1)

fun RecurrenceSelection.toTaskFields(): Pair<RecurrenceType?, String?> = when (preset) {
    RecurrencePreset.NONE -> null to null
    RecurrencePreset.DAILY -> RecurrenceType.RRULE to "FREQ=DAILY"
    RecurrencePreset.WEEKLY -> RecurrenceType.RRULE to "FREQ=WEEKLY"
    RecurrencePreset.MONTHLY -> RecurrenceType.RRULE to "FREQ=MONTHLY"
    RecurrencePreset.EVERY_N_DAYS -> RecurrenceType.RRULE to "FREQ=DAILY;INTERVAL=$n"
    RecurrencePreset.AFTER_COMPLETION_N_DAYS -> RecurrenceType.AFTER_COMPLETION to n.toString()
}

// Unrecognized RRULE strings (anything not generated by the presets above) fall back to NONE for
// display purposes rather than crashing — this is a preset picker, not a general RRULE parser.
fun recurrenceSelectionFromTask(recurrenceType: RecurrenceType?, recurrenceRule: String?): RecurrenceSelection {
    if (recurrenceType == null || recurrenceRule == null) return RecurrenceSelection(RecurrencePreset.NONE)
    return when (recurrenceType) {
        RecurrenceType.AFTER_COMPLETION ->
            RecurrenceSelection(RecurrencePreset.AFTER_COMPLETION_N_DAYS, recurrenceRule.toIntOrNull() ?: 1)
        RecurrenceType.RRULE -> when {
            recurrenceRule == "FREQ=DAILY" -> RecurrenceSelection(RecurrencePreset.DAILY)
            recurrenceRule == "FREQ=WEEKLY" -> RecurrenceSelection(RecurrencePreset.WEEKLY)
            recurrenceRule == "FREQ=MONTHLY" -> RecurrenceSelection(RecurrencePreset.MONTHLY)
            recurrenceRule.startsWith("FREQ=DAILY;INTERVAL=") ->
                RecurrenceSelection(RecurrencePreset.EVERY_N_DAYS, recurrenceRule.substringAfter("INTERVAL=").toIntOrNull() ?: 1)
            else -> RecurrenceSelection(RecurrencePreset.NONE)
        }
    }
}
